---
title: "Reading data from the web"
author: "Zixuan Zhang"
date: "2023-10-12"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = 
  read_html(nsduh_url)
```



```{r}
marj_use_df =
  nsduh_html |> 
  html_table() |> 
  first() |> 
  slice(-1)
  
```

import star wars
```{r}
swm_url =
  "https://www.imdb.com/list/ls070150896/"

swm_html = 
  read_html(swm_url)
```


```{r}
swm_html |> 
  html_elements(".lister-item-header a") |>
  html_text()

swm_tittle = 
  swm_html |>
  html_elements(".lister-item-header a") |>
  html_text()

swm_gross = 
  swm_html |>
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |>
  html_text()

swm_df = 
  tibble(
    title = swm_tittle,
    gross_rev = swm_gross
  )

```


```{r}
nyc_water_df =
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content()
```

```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
        query = list("$limit" = 5000)) |> 
  content()
      
```

```{r}
 poke_df = 
  GET("http://pokeapi.co/api/v2/pokemon/ditto") |>
  content()
```

